retail/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('auth/login');
});

 Auth::routes();
Route::get('/reg','adminController@register')->name('reg');
Route::get('/home', 'HomeController@index')->name('home');


Route::middleware(['auth','verified'])->group(function () {

		Route::resource('productos','ProductosController');
		Route::resource('ventas','ventasController');
		Route::resource('clientes','clientesController');
		
		//ALTA A PROVEDORES-----------------
		Route::get('/storeProvedor','adminController@createProvedor')->name('storeProvedor');
		Route::get('/storeCategoria','adminController@createCategoria')->name('storeCategoria');
		Route::get('/storeLinea','adminController@createLinea')->name('storeLinea');
		Route::get('/storeMarca','adminController@createMarca')->name('storeMarca');
		Route::get('/storeProductos','ProductosController@store')->name('storeProducto');

		Route::post('/uploadImg','adminController@uploadImg');
		Route::post('/buscarProducto','adminController@buscarProducto')->name('buscarProducto');
		Route::post('/buscarXcodigo','adminController@buscarXcodigo')->name('buscarXcodigo');

		Route::post('productos-import-loadExcel','ProductosController@loadExcel')->name('productos.import.loadExcel');
		// Route::post('import-list-excel', 'UserController@importExcel')->name('users.import.excel');
		// Route::post('productos/delete','ProductosController@destroy')->name('deleteProductos');
		Route::get('productos-search','ProductosController@search')->name('productos.search');
		Route::get('clientes-search','clientesController@search')->name('clientes.search');
		
		Route::post('/verProducto','ProductosController@verProducto')->name('verProducto');
		Route::post("/vercliente",'clientesController@verCliente')->name('vercliente');

		Route::post("productos-actualizar",'ProductosController@actualizar')->name('actualizar');
		Route::post("actualizar-cliente",'clientesController@actualizar')->name('actualizar-cliente');
		Route::get('/clientes','clientesController@index')->name('clientes.index');
});

retail/resources/views/forms/clientes.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="position: relative;width: 70%">
	<div id="div_alert"></div>
		@if(session('success'))
	<div class="alert alert-success alert-dismissible fade show">
		<h3>{{session('success')}}</h3>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		</button>
	</div>
		@endif
		@if(session('error'))
	<div class="alert alert-danger alert-dismissible fade show">
		<h3>{{session('error')}}</h3>
		<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		    <span aria-hidden="true">&times;</span>
		</button>
	</div>
	@endif

	<div class="row justify-content-center">
	    <div class="col-md-12">
		    <div class="card" style="width: 150%;margin-left: -80px">
		       	<div class="card-header" style="background-color:#007bff">
		        		<h4 class="text-light">Clientes <i class="fa fa-users"></i></h4>
		        </div>
	        	<div class="card-body">
	        		<ul class="app-breadcrumb breadcrumb" class="text-dark" style="float: right;color: white">
	                  <li class="breadcrumb-item"><a href="{{route('home')}}"><i class="fa fa-home fa-lg"></i></a></li>
	                  <li class="breadcrumb-item"><a href="{{route('clientes.index')}}" class="text-dark">clientes</a></li>
	                </ul>
	                

	                <div class="row">
	              		<div class="col">
	              			<button class="btn btn-sm btn-primary" id="agregarCliente"><i class="fa fa-plus"></i> Cliente</button>
	              		</div>
	              		<div class="col">
	              			
	              		</div>
	              		<div class="col-4">
	              			 <form class="form-inline" action="{{route('clientes.search')}}" method="GET">
							    <input class="form-control mr-sm-2" type="search" name="busqueda" placeholder="Buscar..." aria-label="Buscar">
							    <button class="btn btn-success" type="submit"><i class="fa fa-search"></i></button>
							  </form>
	              		</div>
	              		<!-- fin clas row -->
	              	</div>
	              	<br>
	              		<div class="table-responsive" >
					  <table class="table table-striped table-bordered">
					    	<thead class="table-dark ">
				                  <tr>   
					                   <th>Foto</th>
								       <th>Nombre</th>
								       <th>Apellidos</th>
								       <th>Municipio</th>
								       <th>Localidad</th>
								       <th>Calle</th>
								       <th>Telefono</th>
								       <th>Correo</th>
								       <th>Usuario</th>
								       <th>Status</th>
								       <th style="width: 10%"><i class="fa fa-gears"></i></th>
				                  </tr>
				                </thead>
				                <tbody>
				                	@foreach($clientes as $cliente)
				                	<tr scope="row">
					                	<td><img src="public/img/{{$cliente->foto}}" class="imgRedonda"></td>
						              	<td>{{$cliente->nombre}}</td>
						              	<td>{{$cliente->apellidos}}</td>
						              	<td>{{$cliente->municipio}}</td>
						              	<td>{{$cliente->localidad}}</td>
						              	<td>{{$cliente->calle}}</td>
						              	<td>{{$cliente->telefono}}</td>
						              	<td>{{$cliente->correo}}</td>
						              	<td>{{$cliente->usuarioApp}}</td>
						              	<td>{{$cliente->status}}</td>
						              	<td class="td_imgs" >
						              		<form action="{{ route('clientes.destroy',$cliente->id) }}" method="post" class="btnAction">
						              			 @csrf
	                 							 @method('DELETE')
						              			<button class="btn btn-sm btn-danger" ><i class="fa fa-trash"></i></button>
						              		</form>

						              		<form action="{{route('vercliente') }}" method="post" class="btnAction">
						              			 @csrf
	                 							 <input type="hidden" name="id" value="{{$cliente->id}}">
						              			<button class="btn btn-sm btn-success" ><i class="fa fa-pencil-square"></i></button>
						              		</form>
						              	</td>
					              	</tr>
					              	@endforeach

				                </tbody>
					  </table>
					  {!!$clientes->render() !!}
					</div>

<style type="text/css">
	.btnAction{width: 48%;display: inline-block;}
</style>


	              	</div>
	        	</div>

		    </div> <!-- fin card -->
	    </div><!-- fin col-md-12 -->
	</div><!-- fin content-center -->

</div><!-- fin div container -->



<style type="text/css">
	.imgRedonda {
    width:40px;
    height:42px;
    border-radius:140px;
    border:2px solid #666;
}
.imgPerfil{
	width:60px;
    height:62px;
    border-radius:140px;
    border:2px solid #666;
}
</style>









<!--window modal ######modal clientes################-->
  <div class="modal fullscreen-modal fade" id="modal_clientes" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true" >
    <div class="modal-dialog modal-lg" role="document">
      <div class="modal-content" >
      	<div class="modal-header text-light" style="background-color: #28a745;" >
      		<h1><i class="fa fa-plus"></i> Cliente <i class="app-menu__icon fa fa-user"></i></h1>
      		<span id="imgParaPerfil"></span>
      	</div>
        <div class="modal-body">
        	<div id="div_alert2"></div>
        	<form action="{{route('clientes.store')}}" method="POST">
        		@csrf
        		<div class="row">

				    <div class="col">
						<label for="nombre">Nombre</label>
		        		<input type="text" name="nombre" class="form-control" placeholder="Nombre o nombres ">
		        		<label for="apellidos">Apellidos</label>
		        		<input type="text" name="apellidos" class="form-control" placeholder="apellidos">
						<label for="municipio">Municipio</label>
						<input type="text" name="municipio" class="form-control" placeholder="municipio o C.P.">
		        		<label for="localidad">Localidad</label>
		        		<input type="text" name="localidad" class="form-control" placeholder="Localidad">
						<label for="calle">Calle</label>
		        		<input type="text" name="calle" class="form-control" placeholder="Nombre y número">
				    </div>

				    <div class="col">

				      	<label for="telefono">teléfono</label>
		        		<input type="tel" name="telefono" class="form-control" >

		        		<label for="correo">Correo</label>
		        		<input type="email" name="correo" class="form-control">

						<label for="usuarioApp">Usuario Para la App</label>
		        		<input type="text" name="usuarioApp" class="form-control">

						<label for="password">Contraseña</label>
		        		<input type="password" name="password"  class="form-control">

		        		<label for="foto">Foto</label>
		        		<input type="text" name="foto" id="foto" class="form-control" readonly="" value="default.png">
				 </div>

			</div>
        		
		       	<br><br>
	        	<button type="submit" class="btn btn-success" style="float: right;">Guardar</button>
        	</form>

        	<form enctype="multipart/form-data" id="formsubirFoto" method="post">
        		<label for="imagen"><b>Subir foto:</b></label>
			  <input type="file" name="imagen" id="imagen" />
			  <button  type="submit" class="btn btn-primary" id="subirImg">subir</button>
        	</form>
		  


        </div>
      </div>
    </div>
  </div>











@endsection
@section('script')
<script type="text/javascript">
/////-----------------------para subir foto
	$("#formsubirFoto").on("submit", function(e){
	            e.preventDefault();
	            var f = $(this);
	            var formData = new FormData(document.getElementById("formsubirFoto"));
	            formData.append("dato", "valor");
	            //formData.append(f.attr("name"), $(this)[0].files[0]);
	            $.ajax({
	                url: "{{url('/uploadImg')}}",
	                type: "post",
	                dataType: "",
	                data: formData,
	                cache: false,
	                contentType: false,
		     processData: false
	            }).done(function(e){
					// alert(e.nombre);
					if (e.status=="success") {

						$("#foto").val(e.nombre);
						$("#imgParaPerfil").html('<img src="public/img/'+e.nombre+'" class="imgPerfil">');
						$("#div_alert2").html("<div class='alert alert-success' role='alert'>IMAGEN Cargado correctamente.</div>");
						setTimeout(function(){
				        $( "#div_alert2").html('');
				        }, 3500);
					}else{
						$("#div_alert2").html("<div class='alert alert-danger' role='alert'>Error al cargar.</div>");
						setTimeout(function(){
				        $( "#div_alert2").html('');
				        }, 3500);
					}
		}).fail(function (jqXHR, exception) {
	                // Our error logic here
	                console.log(exception);
	            });
	        });
//------------------------------------------------------------------------------------------------------






//------------- minimizar menu------------------------------------
	$("#btn_toggle").trigger("click");
//-------------------------------------------------------

$("#agregarCliente").click(function(){
	$("#modal_clientes").modal('show');
});
</script>
@endsection

retail/resources/views/forms/edit-clientes.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="position: relative;width: 70%">
	<div id="div_alert"></div>
		@if(session('success'))
		<div class="alert alert-success alert-dismissible fade show">
			<h3>{{session('success')}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
		@if(session('error'))
		<div class="alert alert-danger alert-dismissible fade show">
			<h3>{{session('error')}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif




	    <div class="row justify-content-center">
	        <div class="col-md-12">
	        	
	            <div class="card" style="width: 150%;margin-left: -80px">
	            	<div class="card-header" style="background-color:#20c997">
	            		
	            		<span id="Perfil"><img src="public/img/{{$cliente->foto}}" class="imgPerfil" ></span>
	            		<h4 class="text-light" style="float: right;">Cliente {{$cliente->id}}</h4>
	            	</div>
	            	<div class="card-body">
							<style type="text/css">
							.imgPerfil{
								
								position: absolute;float: right;
								width:60px;
							    height:62px;
							    border-radius:140px;
							    border:2px solid #666;
							}
							</style>
	            		<div id="div_alert2"></div>
			        	<form action="{{route('actualizar-cliente')}}" method="POST">
			        		@csrf
			        		<input type="hidden" name="id" value="{{$cliente->id}}">
			        		<div class="row">

							    <div class="col">
									<label for="nombre">Nombre</label>
					        		<input type="text" name="nombre" class="form-control" value="{{$cliente->nombre}}">
					        		<label for="apellidos">Apellidos</label>
					        		<input type="text" name="apellidos" class="form-control" value="{{$cliente->apellidos}}">
									<label for="municipio">Municipio</label>
									<input type="text" name="municipio" class="form-control" value="{{$cliente->municipio}}">
					        		<label for="localidad">Localidad</label>
					        		<input type="text" name="localidad" class="form-control" value="{{$cliente->localidad}}">
									<label for="calle">Calle</label>
					        		<input type="text" name="calle" class="form-control" value="{{$cliente->calle}}">
							    </div>

							    <div class="col">

							      	<label for="telefono">teléfono</label>
					        		<input type="tel" name="telefono" class="form-control" value="{{$cliente->telefono}}">

					        		<label for="correo">Correo</label>
					        		<input type="email" name="correo" class="form-control" value="{{$cliente->correo}}">

									<label for="usuarioApp">Usuario Para la App</label>
					        		<input type="text" name="usuarioApp" class="form-control" value="{{$cliente->usuarioApp}}">

									<label for="password">Contraseña</label>
					        		<input type="password" name="password"  class="form-control" readonly="" value="{{$cliente->password}}">

					        		<label for="foto">Foto</label>
					        		<input type="text" name="foto" id="foto" class="form-control" readonly="" value="{{$cliente->foto}}">
							 </div>

						</div>
			        		
					       	<br><br>
				        	<button type="submit" class="btn btn-success" style="float: right;">Guardar</button>
			        	</form>

			        	<form enctype="multipart/form-data" id="formsubirFoto" method="post">
			        		<label for="imagen"><b>Subir foto:</b></label>
						  <input type="file" name="imagen" id="imagen" />
						  <button  type="submit" class="btn btn-primary" id="subirImg">subir</button>
			        	</form>
		  
	           		</div>
	        </div> 
	            <!-- fin card -->
	        </div>

	    </div>
	</div>
@endsection
@section('script')
<script type="text/javascript">
	//-----------------------------------------------------------------------------
	$("#formsubirFoto").on("submit", function(e){
	            e.preventDefault();
	            var f = $(this);
	            var formData = new FormData(document.getElementById("formsubirFoto"));
	            formData.append("dato", "valor");
	            //formData.append(f.attr("name"), $(this)[0].files[0]);
	            $.ajax({
	                url: "{{url('/uploadImg')}}",
	                type: "post",
	                dataType: "",
	                data: formData,
	                cache: false,
	                contentType: false,
		     processData: false
	            }).done(function(e){
					// alert(e.nombre);
					if (e.status=="success") {
						$("#foto").val(e.nombre);
						$("#Perfil").html('<img src="public/img/'+e.nombre+'" class="imgPerfil" >');
						$("#div_alert2").html("<div class='alert alert-success' role='alert'>IMAGEN Cargado correctamente.</div>");
						setTimeout(function(){
				        $( "#div_alert2").html('');
				        }, 3500);
					}else{
						$("#div_alert2").html("<div class='alert alert-danger' role='alert'>Error al cargar.</div>");
						setTimeout(function(){
				        $( "#div_alert2").html('');
				        }, 3500);
					}
		}).fail(function (jqXHR, exception) {
	                // Our error logic here
	                console.log(exception);
	            });
	        });


//-------------mostrar modales  agregar------------------------------------
	$("#btn_toggle").trigger("click");
//-------------------------------------------------------
</script>
@endsection

retail/resources/views/forms/edit-productos.blade.php
@extends('layouts.app')
@section('content')
<div class="container" style="position: relative;width: 70%">
	<div id="div_alert"></div>
		@if(session('success'))
		<div class="alert alert-success alert-dismissible fade show">
			<h3>{{session('success')}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
		@if(session('error'))
		<div class="alert alert-danger alert-dismissible fade show">
			<h3>{{session('error')}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif
		@if($msj)
			<div class="alert alert-info alert-dismissible fade show">
			<h3>{{$msj}}</h3>
			<button type="button" class="close" data-dismiss="alert" aria-label="Close">
			    <span aria-hidden="true">&times;</span>
			</button>
		</div>
		@endif

	    <div class="row justify-content-center">
	        <div class="col-md-12">
	        	
	            <div class="card" style="width: 150%;margin-left: -80px">
	            	<div class="card-header" style="background-color:#20c997">
	            		<h4 class="text-light">Producto Id->{{$producto->id}} {{$producto->descripcion_articulo}}</h4>
	            	</div>
	            	<div class="card-body">

	            	<form action="{{route('actualizar')}}" method="POST">
  						@csrf
	            		<input type="hidden" name="id" value="{{$producto->id}}">
	            	<div class="row">
	            		<div class="col-3">
	            			<label>Clave</label>
	            			<input type="number" name="clave" value="{{$producto->clave}}" class="form-control">

	            			<label>Descripción</label>
	            			<input type="text" name="descripcion_articulo" value="{{$producto->descripcion_articulo}}" class="form-control">

	            			<label>unidad</label>
	            			<select name="unidad" id="unidad" class="form-control">
	            				<option selected="true">{{$producto->unidad}}</option>
								<option>Pieza</option>
								<option>Kilogramo</option>
								<option>Litro</option>
								<option>Gramo</option>
								<option>Caja</option>
								<option>Paquete</option>
							</select>

							<label for="precio_compra">precio a la compra</label>
			        		<input type="number" name="precio_compra" class="form-control" value="{{$producto->precio_compra}}">

							<label for="precio_venta">precio a la venta</label>
			        		<input type="number" name="precio_venta" class="form-control" value="{{$producto->precio_venta}}">
	            		</div>

	            		<div class="col-3">
	            			<label for="mayoreo_1">Mayoreo 1</label>
		        		<input type="range" name="mayoreo_1" id="mayoreo_1"  class="custom-range  w-75" min="0" max="100" value="{{$producto->mayoreo_1}}"><span id="span1">{{$producto->mayoreo_1}}</span><span><b>%</b></span>

		        		<label for="mayoreo_2">Mayoreo 2</label>
		        		<input type="range" name="mayoreo_2" id="mayoreo_2" class="custom-range  w-75" min="0" max="100" value="{{$producto->mayoreo_2}}"><span id="span2">{{$producto->mayoreo_2}}</span><span><b>%</b></span>

						<label for="mayoreo_3">Mayoreo 3</label>
		        		<input type="range" name="mayoreo_3" id="mayoreo_3" class="custom-range w-75" min="0" max="100" value="{{$producto->mayoreo_3}}"><span id="span3">{{$producto->mayoreo_3}}</span><span><b>%</b></span>

						<label for="mayoreo_4">Mayoreo 4</label>
		        		<input type="range" name="mayoreo_4" id="mayoreo_4" class="custom-range w-75" min="0" max="100" value="{{$producto->mayoreo_4}}"><span id="span4">{{$producto->mayoreo_4}}</span><span><b>%</b></span>

		        		<label for="codigo_sat">código SAT</label>
		        		<input type="number" name="codigo_sat" class="form-control" placeholder="Código SAT" value="{{$producto->codigo_sat}}">

						<label for="proveedor">proveedor</label>
						<select name="proveedor" class="form-control">
							@foreach($provedores as $provedor)
								<option value="{{$provedor->id}}">{{$provedor->nombres}}</option>
							@endforeach
						</select>
	            		</div>

	            	<div class="col">
						<label for="categoria">Categoria</label>
		        		<select name="categoria" class="form-control">
		        			@foreach($categorias as $categoria)
		        				@if($producto->categoria==$categoria->id)
								<option value="{{$producto->categoria}}">{{$categoria->nombre}}</option>
								@endif
							@endforeach
		        			
							@foreach($categorias as $categoria)
								@if($categoria->id != $producto->categoria )
								<option value="{{$categoria->id}}">{{$categoria->nombre}}</option>
								@endif
							@endforeach
						</select>
		        		<label for="linea">linea</label>
		        			<select name="linea" class="form-control">
							@foreach($lineas as $linea)
		        				@if($producto->linea==$linea->id)
								<option value="{{$producto->linea}}">{{$linea->nombre}}</option>
								@endif
							@endforeach
		        			
							@foreach($lineas as $linea)
								@if($linea->id != $producto->linea )
								<option value="{{$linea->id}}">{{$linea->nombre}}</option>
								@endif
							@endforeach

						</select>
						<label for="marca">Marca</label>
		        			<select name="marca" class="form-control">
							@foreach($marcas as $marca)
		        				@if($producto->marca==$marca->id)
								<option value="{{$producto->marca}}">{{$marca->nombre}}</option>
								@endif
							@endforeach
		        			
							@foreach($marcas as $marca)
								@if($marca->id != $producto->marca )
								<option value="{{$marca->id}}">{{$marca->nombre}}</option>
								@endif
							@endforeach
						</select>
						<label for="existencia">existencia</label>
		        		<input type="number" name="existencia" class="form-control" value="{{$producto->existencia}}">

						<label for="local">Local</label>
		        		<select name="local" class="form-control">
		        			
		        			@foreach($locales as $local)
		        				@if($producto->local==$local->id)
								<option value="{{$producto->local}}">{{$local->nombre}}-{{$local->descripcion}}</option>
								@endif
							@endforeach
		        			
							@foreach($locales as $local)
								@if($local->id != $producto->local )
								<option value="{{$local->id}}">{{$local->nombre}}-{{$local->descripcion}}</option>
								@endif
							@endforeach
		        		</select>
				</div>
					<div class="col">
					<label for="ubicacion_producto">Ubicación del producto</label>
					<input type="text" name="ubicacion_producto" id="ubicacion_producto" class="form-control" readonly="true" style="font-size: 70%" value="{{$producto->ubicacion_producto}}">
					<select class="col-3" id="pasillo">
						<option>Pasillo 0</option>
						<option>Pasillo 1</option>
						<option>Pasillo 2</option>
						<option>Pasillo 3</option>
						<option>Pasillo 4</option>
					</select>
					<select class="col-3" id="anden">
						<option>Anden 0</option>
						<option>Anden 1</option>
						<option>Anden 2</option>
						<option>Anden 3</option>
						<option>Anden 4</option>
					</select>
					<select class="col-3" id="vitrina">
						<option>Vitrina 0</option>
						<option>Vitrina 1</option>
						<option>Vitrina 2</option>
						<option>Vitrina 3</option>
						<option>Vitrina 4</option>
					</select>
					<br>

					<label for="palabra_clave">Palabras clave</label>
					<input type="text" name="palabra_clave" class="form-control" value="{{$producto->palabra_clave}}" >

					<label for="codigo_barra">Código de barra</label>
					<input type="number" name="codigo_barra" class="form-control" readonly="true" value="{{$producto->codigo_barra}}">
					<label for="fotos">Imagenes</label>
					<input type="text" name="fotos" id="fotos" class="form-control" readonly="" value="{{$producto->fotos}}">

				</div>
				<div class="col" style="overflow-y: scroll;height:320px">
					<div class="card-header"><h4>Imagenes</h4></div>
					<p><?php 
					$fotos=$producto->fotos;
					$fotos = explode(",", $fotos);
					foreach ($fotos as $foto) {
						?>
						<span class="text-success">{{$foto}}</span><br>
						<img src="public/img/{{$foto}}" style="width: 50%"><br>
						<?php
					}
					
					?></p>
					
				</div>
	        	</div>
	        <br><br>
	        <button type="submit" class="btn btn-success" id="guardarProducto" style="float: right;">Guardar</button>

	    </form>
	    <form enctype="multipart/form-data" id="formuploadajax" method="post">
        		<label for="imagen"><b>Subir imagen:</b></label>
			  <input type="file" name="imagen" id="imagen" />
			  <button  type="submit" class="btn btn-primary" id="subirImg">subir</button>
        	</form>
	            </div>
	        </div> 
	            <!-- fin card -->
	        </div>

	    </div>
	</div>
@endsection
@section('script')
<script type="text/javascript">
	var imagen="";
	var cont=0;

//-----------------------------------------------------------------------------
	$("#formuploadajax").on("submit", function(e){
	            e.preventDefault();
	            var f = $(this);
	            var formData = new FormData(document.getElementById("formuploadajax"));
	            formData.append("dato", "valor");
	            //formData.append(f.attr("name"), $(this)[0].files[0]);
	            $.ajax({
	                url: "{{url('/uploadImg')}}",
	                type: "post",
	                dataType: "",
	                data: formData,
	                cache: false,
	                contentType: false,
		     processData: false
	            }).done(function(e){
					// alert(e.nombre);
					if (e.status=="success") {
						if (cont==0) {
							if ($("#fotos").val()=="ninguno") {
								imagen=e.nombre;
							}else{
								imagen=$("#fotos").val()+","+e.nombre;
							}
							
						}else{
							imagen=imagen+","+e.nombre;
						}
						cont++;
						
						$("#fotos").val(imagen);
						$("#div_alert").html("<div class='alert alert-success' role='alert'>IMAGEN Cargado correctamente.</div>");
						setTimeout(function(){
				        $( "#div_alert").html('');
				        }, 3500);
					}else{
						$("#div_alert").html("<div class='alert alert-danger' role='alert'>Error al cargar.</div>");
						setTimeout(function(){
				        $( "#div_alert").html('');
				        }, 3500);
					}
		}).fail(function (jqXHR, exception) {
	                // Our error logic here
	                console.log(exception);
	            });
	        });



$("#guardarProducto").click(function(){
		cont=0;
	});


//------------para sliders------------------
	$("#mayoreo_1").change(function(){
		$("#span1").html($(this).val());
	});
	$("#mayoreo_2").change(function(){
		$("#span2").html($(this).val());
	});
	$("#mayoreo_3").change(function(){
		$("#span3").html($(this).val());
	});
	$("#mayoreo_4").change(function(){
		$("#span4").html($(this).val());
	});
	$("#pasillo,#anden,#vitrina").on('change',function(){
		var ubicacion=$("#pasillo").val()+","+$("#anden").val()+","+$("#vitrina").val();
		$("#ubicacion_producto").val(ubicacion);
	});
//-------------mostrar modales  agregar------------------------------------
	$("#btn_toggle").trigger("click");
//-------------------------------------------------------
</script>
@endsection